services:
  garage:
    image: dxflrs/garage:v1.0.0
    container_name: garage-dev
    restart: unless-stopped
    ports:
      - "3900:3900"  # Admin API
      - "3901:3901"  # RPC
      - "3902:3902"  # S3 API
    environment:
      GARAGE_RPC_SECRET: "1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e30c0de809b03923bff9b"
      GARAGE_RPC_BIND_ADDR: "0.0.0.0:3901"
      GARAGE_RPC_PUBLIC_ADDR: "127.0.0.1:3901"
      GARAGE_ADMIN_TOKEN: "test_admin_token_for_integration_tests_secure"
    volumes:
      - garage_data:/var/lib/garage/data
      - garage_meta:/var/lib/garage/meta
      - ./garage.toml:/etc/garage.toml:ro

volumes:
  garage_data:
    driver: local
  garage_meta:
    driver: local