metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

replication_mode = "1"  # Single node pour développement
compression_level = 1

rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "1799bccfd7411eddcf9ebd316bc1f5287ad12a68094e30c0de809b03923bff9b"

[s3_api]
s3_region = "garage"
api_bind_addr = "0.0.0.0:3902"
root_domain = ".s3.localhost"

[admin]
api_bind_addr = "0.0.0.0:3900"
admin_token = "test_admin_token_for_integration_tests_secure"
metrics_token = "test_metrics_token"
